name: ci-golang-workflow

on:
  push:
    branches:
      - develop
      

jobs: 
  checkout-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup do ambiente Go 
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Executar testes
        run: go test

  

